name: 'Terraform Plan'

on:
  pull_request:
    paths:
      - '**/*.tf'  # Trigger the workflow when .tf files are modified

env:
  TF_CLOUD_ORGANIZATION: "eshant-hcp-tf-test"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "learn-terraform-github-actions"
  CONFIG_DIRECTORY: "./"  # Directory where your Terraform configuration files are located

jobs:
  terraform:
    if: github.repository != 'hashicorp-education/learn-terraform-github-actions'
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload Configuration
      uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
      id: plan-upload
      with:
        workspace: ${{ env.TF_WORKSPACE }}
        directory: ${{ env.CONFIG_DIRECTORY }}
        speculative: true  # Run a speculative plan

    - name: Create Plan Run
      uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
      id: plan-run
      with:
        workspace: ${{ env.TF_WORKSPACE }}
        configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
        plan_only: true  # Only generate the plan, don't apply

    # Fetch Full Plan Output
    - name: Fetch Full Terraform Plan Output
      id: fetch-plan-output
      run: |
        # Fetch the Run ID from the previous step
        RUN_ID=${{ fromJSON(steps.plan-run.outputs.payload).data.id }}

        # Use curl to get the plan details from Terraform Cloud's API
        curl --silent --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
             --header "Content-Type: application/vnd.api+json" \
             --request GET \
             --url "https://app.terraform.io/api/v2/runs/$RUN_ID/plan" \
             --output plan_output.json
        
        # Extract the plan text from the response
        PLAN_OUTPUT=$(cat plan_output.json | jq -r '.data.attributes.plan.text')
        
        # Save it to a file so we can use it in the next step
        echo "$PLAN_OUTPUT" > terraform_plan_output.txt

    # Step to add comment with the full plan
    - name: Update PR with Full Terraform Plan Output
      uses: actions/github-script@v6
      id: plan-comment
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const planOutput = fs.readFileSync('terraform_plan_output.txt', 'utf8');
          
          // Retrieve existing bot comments for the PR
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          // Find the previous bot comment
          const botComment = comments.find(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('HCP Terraform Plan Output');
          });

          // Prepare the full Terraform plan output comment
          const output = `#### HCP Terraform Plan Output
          \`\`\`
          ${planOutput}
          \`\`\`
          `;

          // If there's an existing bot comment, delete it
          if (botComment) {
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
            });
          }

          // Create a new comment with the full Terraform plan output
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output,
          });
